[SYSTEMML-2101] Fix JMLC robustness for missing fs impl classes
This patch increases the robustness of JMLC for missing file system
classes. Thrown NoClassDefFoundErrors so far passed the exception
handling leading to failures even though the persistent reads are later
replaced by in-memory inputs.