[SYSTEMDS-3414] Fix allocation of large, multi-array dense matrices
This patch fixes the allocation logic for large dense matrix blocks
which internally use multiple arrays of size <= int_max in a row-aligned
manner. While this works well if the row-alignment causes enough head
room to max_integer, the actual maximum allocation is platform-specific.
For example, on the following scenario it failed with
OutOfMemoryError: Requested array size exceeds VM limit:

INT_MAX:   2147483648
ALLOCATED: 2147483646 --> error despite <= int_max

We now leave explicit head room of 8 cells for platform-specific padding
to prevent such errors. The same bound is also applied to the byte
buffers in the lazy write cache (buffer pool).