[MINOR] Throw exception along in IO NoClassDefFoundError
This commit adds the exception of the class missing in the IO exception.
I had issues finding the library missing because this exception was
caught but not passing on the underlying exception